### PR TITLE
updated change log

### PR DESCRIPTION
**Pull request by fieg**

### CODE REVIEW

**Comment by hiddeco** [comment]
Wouldn't it be wise to include PR/issue numbers/hashes in the changelog?

**Comment by fieg** [comment]
+1 for issue numbers (but there aren't any up to this point)

**Comment by hiddeco** [comment]
Also, your list style isn't consistent with the changelog from the `2.0` branch.

`* list item !== list item`

**Comment by fieg** [comment]
We can correct that later on

**Review by hiddeco — APPROVED** [review]

**Pull request merged**
